# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rcomet}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guillaume Dorchies", "Gr\xC3\xA9goire Lejeune"]
  s.date = %q{2011-04-11}
  s.default_executable = %q{rcomet}
  s.description = %q{RComet implement the Bayeux protocole to allow you to create client and/or Comet's server.}
  s.email = %q{guillaume.dorchies@gmail.com}
  s.executables = ["rcomet"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    "History.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rcomet",
    "examples/chart/README.rdoc",
    "examples/chart/chart-cometd.rb",
    "examples/chart/chart.rb",
    "examples/chart/static/chart.rhtml",
    "examples/chat/README.rdoc",
    "examples/chat/chat-cometd.rb",
    "examples/chat/chat.rb",
    "examples/chat/static/chat.rhtml",
    "examples/chat/static/login.rhtml",
    "examples/chat/static/style.css",
    "examples/soapbox/README.rdoc",
    "examples/soapbox/client.rb",
    "examples/soapbox/soapbox-cometd.rb",
    "examples/soapbox/soapbox.rb",
    "examples/soapbox/static/soapbox.rhtml",
    "examples/soapbox/static/style.css",
    "lib/rcomet.rb",
    "lib/rcomet/channel.rb",
    "lib/rcomet/client.rb",
    "lib/rcomet/core_ext.rb",
    "lib/rcomet/rack_adapter.rb",
    "lib/rcomet/server.rb",
    "lib/rcomet/user.rb",
    "rcomet.gemspec",
    "spec/rcomet_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/glejeune/rcomet}
  s.rdoc_options = ["--title", "RComet", "--main", "README.rdoc", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rcomet}
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{RComet is an implementation of the Bayeux protocol in Ruby.}
  s.test_files = [
    "examples/chart/chart-cometd.rb",
    "examples/chart/chart.rb",
    "examples/chat/chat-cometd.rb",
    "examples/chat/chat.rb",
    "examples/soapbox/client.rb",
    "examples/soapbox/soapbox-cometd.rb",
    "examples/soapbox/soapbox.rb",
    "spec/rcomet_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rack>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rack>, [">= 0"])
  end
end

